import { ArrowRight, Check } from "lucide-react";
import { useMemo, useState } from "react";
const interests=["Nature","Culture","Food","Adventure","Wellness","Nightlife"], budgets=["Essential","Comfort","Luxury"], paces=["Slow","Balanced","Full"], stays=["Boutique","Resort","Local stay","Luxury hotel"];
function Choice({active,children,onClick}){return <button type="button" onClick={onClick} className={`flex items-center justify-between border px-4 py-4 text-left text-[9px] uppercase tracking-[.2em] transition ${active?"border-[#f3efe6] bg-[#f3efe6] text-black":"border-white/15 text-white/55 hover:border-white/40 hover:text-white"}`}>{children}{active&&<Check size={13}/>}</button>}
export default function TripPlanner({destination,onGenerate}){
 const [days,setDays]=useState(5),[travellers,setTravellers]=useState(2),[budget,setBudget]=useState("Comfort"),[pace,setPace]=useState("Balanced"),[stay,setStay]=useState("Boutique"),[selected,setSelected]=useState(["Nature","Culture"]),[startDate,setStartDate]=useState("");
 const canGenerate=useMemo(()=>selected.length>0,[selected]); const toggle=i=>setSelected(v=>v.includes(i)?v.filter(x=>x!==i):[...v,i]);
 return <div className="grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="text-[8px] uppercase tracking-[.32em] text-white/35">Journey brief</p><h2 className="mt-5 font-serif text-5xl leading-[.92] tracking-[-.05em] text-[#f3efe6]">Build {destination.name} around you.</h2><p className="mt-6 max-w-sm text-[11px] leading-6 text-white/40">VEYRA will fetch real sights around your destination and shape them into a practical day-by-day route.</p></div><div className="space-y-10 lg:col-span-8">
 <div className="grid gap-6 sm:grid-cols-3"><label className="text-[8px] uppercase tracking-[.25em] text-white/35">Start date<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)} className="mt-3 w-full border border-white/15 bg-transparent p-4 text-sm text-white outline-none [color-scheme:dark]"/></label><label className="text-[8px] uppercase tracking-[.25em] text-white/35">Days<input type="number" min="2" max="14" value={days} onChange={e=>setDays(Math.max(2,Math.min(14,+e.target.value||2)))} className="mt-3 w-full border border-white/15 bg-transparent p-4 text-xl outline-none"/></label><label className="text-[8px] uppercase tracking-[.25em] text-white/35">Travellers<input type="number" min="1" max="12" value={travellers} onChange={e=>setTravellers(Math.max(1,Math.min(12,+e.target.value||1)))} className="mt-3 w-full border border-white/15 bg-transparent p-4 text-xl outline-none"/></label></div>
 <div><p className="mb-4 text-[8px] uppercase tracking-[.25em] text-white/35">What matters to you?</p><div className="grid gap-2 sm:grid-cols-3">{interests.map(i=><Choice key={i} active={selected.includes(i)} onClick={()=>toggle(i)}>{i}</Choice>)}</div></div>
 <div className="grid gap-8 md:grid-cols-3">{[["Budget",budgets,budget,setBudget],["Pace",paces,pace,setPace],["Stay",stays,stay,setStay]].map(([label,items,value,setter])=><div key={label}><p className="mb-4 text-[8px] uppercase tracking-[.25em] text-white/35">{label}</p><div className="space-y-2">{items.map(i=><Choice key={i} active={value===i} onClick={()=>setter(i)}>{i}</Choice>)}</div></div>)}</div>
 <button disabled={!canGenerate} onClick={()=>onGenerate({days,travellers,budget,pace,stay,interests:selected,startDate})} className="group flex w-full items-center justify-between border-y border-white/20 py-6 text-left disabled:opacity-30"><span><span className="block text-[8px] uppercase tracking-[.28em] text-white/35">Real places · shaped to your pace</span><span className="mt-2 block font-serif text-3xl text-[#f3efe6]">Build my journey</span></span><span className="flex h-12 w-12 items-center justify-center rounded-full border border-white/25 transition group-hover:bg-white group-hover:text-black"><ArrowRight size={16}/></span></button>
 </div></div>;
}
